@startuml afficher pièce

actor "Utilisateur" as u
participant "Esidom front-end" as fe
participant "Esidom middleware" as m
participant "Home Assistant" as ha

u -> fe: Afficher une pièce
fe -> m: GET /room/{room_id}
m -> ha: ???
ha --> m: ???
m --> fe: 200 - Ok
fe --> u: La pièce est affichée

@enduml