@startuml afficher objet

actor "Utilisateur" as u
participant "Esidom front-end" as fe
participant "Esidom middleware" as m
participant "Home Assistant" as ha
participant "Objet connecté" as o

u -> fe: Afficher objet
fe -> m: GET /device/{device_id}
m -> ha: ???
ha -> o: ???
o --> ha: ??
ha --> m: ???
m --> fe: 200 - Ok
fe --> u: Affiche les informations de l'objet

@enduml