@startuml désappairer

actor "Utilisateur" as u
participant "Esidom front-end" as fe
participant "Esidom back-end" as m
participant "Home Assistant" as ha

u -> fe: Supprimer objet connecté
fe -> m: PATCH /device/{device_id}\nData: { activated: false}
m -> ha: WS: {type: "config/device_registry/update", device_id: "{device_id}",disabled_by: "user"}
ha --> m: WS: {type: "result", success: true,...}
m --> fe: 204 - No Content
fe --> u: Objet supprimé

u -> fe: Restaurer objet connecté
fe -> m: PATCH /device/{device_id}\nData: { activated: true}
m -> ha: WS: {type: "config/device_registry/update", device_id: "{device_id}",disabled_by: "null"}
ha --> m: WS: {type: "result", success: true,...}
m --> fe: 204 - No Content
m -> ha: WS: Redémarrer
m --> fe: WS: Je vais redémarrer
fe --> u: ESIDOM va redémarrer
ha -> ha: Redémarrer
fe -> m: WS: Demande statut
m -> ha: WS: Demande statut
ha --> m: WS: Réponse statut
m --> fe: WS: Réponse statut
fe --> u: Objet restauré

@enduml