@startuml désactiver entité

actor "Utilisateur" as u
participant "Esidom front-end" as fe
participant "Esidom back-end" as m
participant "Home Assistant" as ha

u -> fe: Désactiver une entité
fe -> m: PATCH /entity/{entity_id}\nData: { activated: false}
m -> ha: ???
ha --> m: ???
m --> fe: 204 - No Content
fe --> u: Entité désactivée

u -> fe: Restaurer une entité
fe -> m: PATCH PATCH /entity/{entity_id}\nData: { activated: true}
m -> ha: ???
ha --> m: ???
m --> fe: 204 - No Content
fe --> u: Veuillez redémarrer Home Assistant
u -> fe: Redémarrer
fe -> m: ??
m -> ha: ??
ha -> ha: Redémarrer
fe -> m: get statut
m -> ha: get statut
ha --> m: response statut
m --> fe: response statut
fe --> u: Entité restaurée

@enduml