@startuml déverrouiller l'application

actor "Utilisateur" as u
participant "Esidom front-end" as fe
participant "Esidom back-end" as m
participant "Home Assistant" as ha

u -> fe: Déverrouiller l'application
fe -> m: POST /auth\n\
{\n\
  username: <String>,\n\
  paswword: <String>\n\
}
m -> ha: POST /auth/login_flow
ha --> m: 200 - Ok \n{\n"flow_id": "{flow_id}"\n}
m -> ha: POST /auth/login_flow/{flow_id} \n {\n"username":"{username}",\n"password":"{password}"\n}
ha --> m: 200 - Ok \n { \n "result": "{result_auth}"\n}
m -> ha: POST /auth/token \n FormData :\ncode:{result_auth}\ngrant_type:authorization_code
ha --> m: 200 - Ok \n {\n "access_token":"{access_token}"\n}
m --> fe: 201 - Created
fe --> u: L'application est déverrouiller

@enduml