@startuml afficher manuel

actor "Utilisateur" as u
participant "Esidom front-end" as fe
participant "Esidom middleware" as m
participant "Home Assistant" as ha

u -> fe: Afficher un manuel
fe -> m: GET /manual/{ean}
m -> ha: ???
ha --> m: ???
m --> fe: 200 - Ok
fe --> u: Le manuel est affiché

@enduml