@startuml lister objets

actor "Utilisateur" as u
participant "Esidom front-end" as fe
participant "Esidom middleware" as m
participant "Home Assistant" as ha

u -> fe: Lister les objets
fe -> m: GET /devices
m -> ha: ???
ha --> m: ???
m --> fe: 200 - Ok
fe --> u: Les objets sont listés

@enduml