@startuml modifier groupe

actor "Utilisateur" as u
participant "Esidom front-end" as fe
participant "Esidom middleware" as m
participant "Home Assistant" as ha

u -> fe: Modifier groupe
fe -> m: PUT /group/{group_id}
Data: {\n\
  name: <String>,\n\
  devices : <list>\n\
}
m -> ha: ???
ha --> m: ???
m --> fe: 200 - Ok
fe --> u: Afficher le groupe modifié

@enduml