@startuml modifier routine

actor "Utilisateur" as u
participant "Esidom front-end" as fe
participant "Esidom middleware" as m
participant "Home Assistant" as ha

u -> fe: Modifier routine
fe -> m: PUT /automation/{automation_id}\n\
Data: ???
m -> ha: POST /api/config/automation/config/{automation_id}
ha --> m: 200 - Ok
m --> fe: 200 - Ok
fe --> u: Afficher routine

@enduml