@startuml supprimer routine

actor "Utilisateur" as u
participant "Esidom front-end" as fe
participant "Esidom middleware" as m
participant "Home Assistant" as ha

u -> fe: Supprimer la routine
fe -> m: DELETE /automation/{automation_id}
m -> ha: DELETE /api/config/automation/config/{automation_id}
ha --> m: 200 - Ok
m --> fe: 204 - No content
fe --> u: La routine est supprimée

@enduml